#!/bin/sh -e 

java -Dsun.java2d.opengl=true -Dsun.java2d.opengl.fbobject=true -cp \
/Users/chrisn/dev/clojure/trunk/clojure.jar:\
/Users/chrisn/dev/clojure-contrib/trunk/clojure-contrib.jar:\
/Users/chrisn/dev/editor/lambinator/lambinator.jar:\
/Users/chrisn/dev/jogl-1.1.1-macosx-universal/lib/jogl.jar:\
/Users/chrisn/dev/jogl-1.1.1-macosx-universal/lib/gluegen-rt.jar:\
 -Djava.library.path=/Users/chrisn/dev/jogl-1.1.1-macosx-universal/lib/\
 -Dcom.apple.eawt.CocoaComponent.CompatibilityMode=false\
 -Dsun.java2d.opengl=true\
 -Dsun.java2d.opengl.fbobject=true\
 -Dsun.java2d.translaccel=true\
  clojure.lang.Repl
