#!/bin/sh -e 
java -server\
 -Dsun.java2d.opengl=true -Dsun.java2d.opengl.fbobject=true -cp \
$CLASSPATH:\
/Users/chrisn/dev/editor/lambinator/lambinator.jar:\
/Users/chrisn/dev/mydoggy-1/lib/mydoggy-api-1.4.2.jar:\
/Users/chrisn/dev/mydoggy-1/lib/mydoggy-plaf-1.4.2.jar:\
/Users/chrisn/dev/mydoggy-1/lib/TableLayout-20050920.jar:\
/Users/chrisn/dev/mydoggy-1/lib/mydoggy-res-1.4.2.jar:\
 -Dcom.apple.eawt.CocoaComponent.CompatibilityMode=false\
 -Dsun.java2d.opengl=true\
 -Dsun.java2d.opengl.fbobject=true\
 -Dsun.java2d.translaccel=true\
  clojure.lang.Repl
