#!/bin/sh 
java -cp lambinator.jar:lib/mydoggy-api-1.4.2.jar:\
lib/mydoggy-plaf-1.4.2.jar:lib/mydoggy-res-1.4.2.jar:lib/TableLayout-20050920.jar\
:$CLASSPATH\
 -Dsun.java2d.opengl=true -Dsun.java2d.opengl.fbobject=true \
 -Dcom.apple.eawt.CocoaComponent.CompatibilityMode=false\
 -Dsun.java2d.opengl=true\
 -Dsun.java2d.opengl.fbobject=true\
 -Dsun.java2d.translaccel=true\
  lambinator.demo
